<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Test Automation" duration-ms="150116" started-at="2021-06-28T10:36:36Z" finished-at="2021-06-28T10:39:06Z">
    <groups>
    </groups>
    <test name="Functional Testing for Ajio" duration-ms="150116" started-at="2021-06-28T10:36:36Z" finished-at="2021-06-28T10:39:06Z">
      <class name="com.qa.testscripts.TC_AjioSearchProduct_01">
        <test-method status="PASS" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testscripts.TC_AjioSearchProduct_01@4520ebad]" name="setUp" is-config="true" duration-ms="92905" started-at="2021-06-28T16:06:37Z" finished-at="2021-06-28T16:08:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.ajio.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="SearchProducts(java.lang.String)[pri:0, instance:com.qa.testscripts.TC_AjioSearchProduct_01@4520ebad]" name="SearchProducts" duration-ms="0" started-at="2021-06-28T16:08:10Z" data-provider="getData" finished-at="2021-06-28T16:08:10Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:110)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:436)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:402)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.qa.utility.ExcelUtility.getRowCount(ExcelUtility.java:23)
	at com.qa.testscripts.TC_AjioSearchProduct_01.getData(TC_AjioSearchProduct_01.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:51)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:41)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchProducts -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testscripts.TC_AjioSearchProduct_01@4520ebad]" name="tearDown" is-config="true" duration-ms="17641" started-at="2021-06-28T16:08:11Z" finished-at="2021-06-28T16:08:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testscripts.TC_AjioSearchProduct_01 -->
      <class name="com.qa.testscripts.TC_AjioCustomerCare_02">
        <test-method status="PASS" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:com.qa.testscripts.TC_AjioCustomerCare_02@5419f379]" name="setUp" is-config="true" duration-ms="36509" started-at="2021-06-28T16:08:28Z" finished-at="2021-06-28T16:09:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[https://www.ajio.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="SearchTopics(java.lang.String)[pri:0, instance:com.qa.testscripts.TC_AjioCustomerCare_02@5419f379]" name="SearchTopics" duration-ms="0" started-at="2021-06-28T16:09:05Z" data-provider="getData" finished-at="2021-06-28T16:09:05Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:110)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:436)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1253)
	at org.testng.internal.Invoker.createParameters(Invoker.java:980)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1070)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:402)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: C:\Users\Priti\Desktop\LP IAT(Batch 8)\SeleniumProject2\src\test\java\com\qa\testdata\testdata.xlsx (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.qa.utility.ExcelUtility.getRowCount(ExcelUtility.java:23)
	at com.qa.testscripts.TC_AjioCustomerCare_02.getData(TC_AjioCustomerCare_02.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:51)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:41)
	... 17 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTopics -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testscripts.TC_AjioCustomerCare_02@5419f379]" name="tearDown" is-config="true" duration-ms="1280" started-at="2021-06-28T16:09:05Z" finished-at="2021-06-28T16:09:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testscripts.TC_AjioCustomerCare_02 -->
    </test> <!-- Functional Testing for Ajio -->
  </suite> <!-- Test Automation -->
</testng-results>
